### ISSUE TITLE
Embed SVG written logo in header

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/dfg.scambi.org#104]
Since we have [a wonderful SVG logo](https://nuvola.scambi.org/s/i4ENfgPiPCap2Gd 'Scambi lettering SVG on Nuvola') with the “Scambi” lettering, it would be wonderful to embed it in the header, instead of the current basic writing in Londrina.

**Comment by traciingu** [comment]
Hi Tommi, I'm just confirming - when you say header, do you mean the navigation bar with the site links?

**Comment by xplosionmind** [comment]
Exactly. In the top left there is “Scambi” written, it would be nice if it appears with our lettering logo.

**Comment by minhuyenhoang** [comment]
This is implemented by Tracy! Awesome work!

**Comment by xplosionmind** [comment]
You are so fast and efficient I really cannot thank you enough. Keep up the great work, the festival is close!

Rock'n'rolllllll!

**Comment by xplosionmind** [comment]
You are so fast and efficient I really cannot thank you enough. Keep up the great work, the festival is close!

Rock'n'rolllllll!
