### ISSUE TITLE
Testing Netlify hosting

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/dfg.scambi.org#15]
To test hosting on [Netlify](https://netlify.com) I created a website at [scambifestival.netlify.app](https://scambifestival.netlify.app). The build fails because of warnings that are treated as errors, as you can see in the [build log](https://app.netlify.com/sites/scambifestival/deploys/62664209be3a43461d7f3cd1).

Unfortunately, Netlify free version does not allow me to add any of you to the team, but I configured very basic environment settings so that at every push of any branch of this repository the website attempts to be built.

I have done this as a non-invasive test. Feel free not to consider it at all if you believe it is not the right solution for our needs.

Sorry for stepping in so directly and abruptly, I hope I did not cause any trouble.

**Comment by xplosionmind** [comment]
Also: I do not intend to cram the repository with many non-relevant issues. Feel free to close them once you have read them!

**Comment by minhuyenhoang** [comment]
The site is built now.
