### ISSUE TITLE
Netlify build fails

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/dfg.scambi.org#54]
Hi! Netlify automatically runs `npm run build` after every push to the master branch. After the latest push, build fails. [Here](https://paste.yunohost.org/raw/ejufinexub) is the log.

Unfortunately, since the project belongs to me and it costs money we do not have to add even one team member, you should be guiding me through the changes I have to make to the config in order to make the build work.

**Comment by minhuyenhoang** [comment]
@xplosionmind I have checked the log and I honestly have no idea why the build failed on Netlify. It can build locally for me, so not quite sure why the error. I noticed something strange is that we have an error on this one when we definitely don't have this ```react-windowed-select``` installed.

<img width="820" alt="Screen Shot 2022-07-10 at 7 52 28 PM" src="https://user-images.githubusercontent.com/57023265/178179987-3774e980-c15e-40d4-8ee5-e0fa49c4fbd7.png">

I will try to delete and reinstall everything to see if Netlify generate the same error.

**Comment by minhuyenhoang** [comment]
Ok so I fixed that dependency error. But then now it's giving me a different error cause by file naming. I will try to fix it.

**Comment by minhuyenhoang** [comment]
@xplosionmind I have fixed all the error and the site is built! Turns out that there were some CSS error in one of the files, if I build it locally, they would be ignored, but Netlify doesn't.

**Comment by xplosionmind** [comment]
> if I build it locally, they would be ignored, but Netlify doesn't.

Aaaaaah I can relate! Lots of trouble with Netlify super strict build rules, I lost tons of hours trying to debug [my website](https://tommi.space 'The virtual representation of Tommi‘s mind')'s logs… I guess it is better this way.

Thanks a lot!
