### ISSUE TITLE
I cannot see anything after building the website

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/dfg.scambi.org#55]
Guys please ignore these issues if you do not have time to help me with my messy non-developer approach.

After running `npm start`, the website builds, but the `localhost:3000` page that opens up is empty… am I doing something wrong?

**Comment by minhuyenhoang** [comment]
Hi @xplosionmind, that is strange. I was able to run it, so I'm not sure why yours is empty. Have you run ```git pull origin main``` to update your local repository before you run the website?

**Comment by xplosionmind** [comment]
> Have you run `git pull origin main` to update your local repository before you run the website?

I did: I get “Already up to date.”

**Comment by xplosionmind** [comment]
It now works. I have no idea why. Thanks anyways.
