### ISSUE TITLE
Drop Google Fonts

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/dfg.scambi.org#78]
I noticed that the website uses Google Fonts. Please, let us self-host and deliver the fonts straight from the website source rather than using Google Fonts.

We pursue a 100% Google free philosophy and, unless there is no alternative, we should keep things this way.

**Comment by minhuyenhoang** [comment]
We can download those fonts to the project local folder, and use them. We just need to give credits.

**Comment by minhuyenhoang** [comment]
The fonts are now self-hosted!
